# Generated by Django 3.0.3 on 2020-03-13 02:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estimated_date_contracted', models.DateTimeField(verbose_name='estimated date contracted')),
                ('date_confirmed', models.DateTimeField(verbose_name='data confirmed')),
            ],
        ),
        migrations.CreateModel(
            name='ContagionPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_sites', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('confirmed_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.ConfirmedCase')),
            ],
        ),
    ]
