# Generated by Django 3.0.3 on 2020-03-13 02:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_site', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
            ],
        ),
        migrations.AlterField(
            model_name='confirmedcase',
            name='date_confirmed',
            field=models.DateTimeField(verbose_name='date confirmed'),
        ),
        migrations.DeleteModel(
            name='ContagionPath',
        ),
        migrations.AddField(
            model_name='contagionsite',
            name='confirmed_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.ConfirmedCase'),
        ),
    ]
